name: Build with Gradlew

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'microsoft'
          cache: 'gradle'
      - name: FIx permissions
        run: chmod +x ./gradlew
      - name: Check code style
        run: ./gradlew ktlintCheck
      - name: Generate docs
        run: ./gradlew dokkaHtml
      - uses: actions/upload-artifact@v2
        name: Save documentation
        with:
          name: docs
          path: build/dokka/
      - name: Build with Gradle
        run: ./gradlew build